### ISSUE TITLE
why we have both mbzirc_arena.world and mbzirc_arena_old.world ?

### ISSUE THREAD

**Issue by k-okada** [tongtybj/mbzirc#16]

**Comment by tongtybj** [comment]
mbzirc_arena.world : 競技場の模様をテクスチャとして立体モデルに貼り付けています。
mbzirc_arena_old.world: 競技場のすべての模様は個々のモデルとして作成しています。そのため、八の字のトラックとグランド間ではわずかな段差があります。

後者はold故に、削除しようと思っていましたが、
前者のmbzirc_arena.worldが陳さんのPC(W540)だとちゃんと表示できないという報告があったため、
作業のため一時的に残しています。
この問題はissue  #7 で議論しています。

岡田先生のPCでは前者のmbzirc_arena.worldはちゃんと表示できていますか？

**Comment by k-okada** [comment]
動いていると思うけど，#7, #8 見てもチョットわからないな．
動いていない -> 何が動いていないかちゃんと書こう．こうなるはずだけど，こうなっていない．最低限画面のキャプチャかoutputのlogをはりつける

**Comment by tongtybj** [comment]
@cretaceous-creature 
could you please try again the mbzirc_arena.world, and explain the problem(attach the image)?

**Comment by cretaceous-creature** [comment]
Sorry for late reply,
Since 8:00, I am having the driving
test today in 府中.
I will try it after I get back to school.

2016年1月13日水曜日、趙 漠居<notifications@github.com>さんは書きました:

**Comment by k-okada** [comment]
please could you please try again the mbzirc_arena.world,
mbzic_task_1.launch, mbzic_task_2.launch, mbzic_task3.launch

--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
Sorry okada sensei,
I am at dorm now and I did not bring the notebook back.
I will send the images tomorrow to explain my situation.
Basically, in the old map the start sign lies in the right of the map,
but in the new map without change of the yaw, the start sign lies in the
bottom.
Then I modified the yaw to make it the same as the old one.

2016-01-13 22:37 GMT+08:00 Kei Okada <notifications@github.com>:

> please could you please try again the mbzirc_arena.world,
> mbzic_task_1.launch, mbzic_task_2.launch, mbzic_task3.launch
>
> --
> ◉ Kei Okada
>
>

**Comment by cretaceous-creature** [comment]
![111](https://cloud.githubusercontent.com/assets/8966553/12312601/1a0a39fc-baa4-11e5-893b-c70c06402cc6.jpg)
![222](https://cloud.githubusercontent.com/assets/8966553/12312603/1ca37cdc-baa4-11e5-9c80-ed523f01630b.jpg)
The first one is the former direction definition, the second one is the new map direction, now I will use the new one and abandon the former one.

**Comment by k-okada** [comment]
Can you fix plugins?

2016年1月14日木曜日、Chen<notifications@github.com>さんは書きました:

> [image: 111]
> <https://cloud.githubusercontent.com/assets/8966553/12312601/1a0a39fc-baa4-11e5-893b-c70c06402cc6.jpg>
> [image: 222]
> <https://cloud.githubusercontent.com/assets/8966553/12312603/1ca37cdc-baa4-11e5-9c80-ed523f01630b.jpg>
> The first one is the former direction definition, the second one is the
> new map direction, now I will use the new one and abandon the former one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tongtybj/mbzirc/issues/16#issuecomment-171486660>.
>


-- 
--
◉ Kei Okada

**Comment by k-okada** [comment]
seems ok
