### ISSUE TITLE
truck model 

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/mbzirc#18]
https://github.com/tongtybj/mbzirc/tree/drone-simulation/jsk_mbzirc_common/gazebo_model/models/truck

**Comment by tongtybj** [comment]
pugin cpp

https://github.com/tongtybj/mbzirc/blob/drone-simulation/jsk_mbzirc_common/src/mbzirc_gazebo_truck_plugin.cpp

**Comment by k-okada** [comment]
thx

**Comment by k-okada** [comment]
you can close this, #23 include truck model
