### ISSUE TITLE
The task orientated directory structure

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/mbzirc#2]
@cretaceous-creature 
I will create trask1/3 directory which contains the drone model, and each task object models(truck for task1 and picking objects for task3).

**Comment by tongtybj** [comment]
@cretaceous-creature 
I will create a new branch, the lastest one(with the commit 8f91c49588fe5ef990485730731cd0db646298c8)

**Comment by cretaceous-creature** [comment]
Ok,
I am also consider to create the folder now

2016年1月5日火曜日、趙 漠居<notifications@github.com>さんは書きました:

**Comment by tongtybj** [comment]
Thanks,

I will commit the change today.

2016-01-05 9:10 GMT+09:00 Chen <notifications@github.com>:

**Comment by cretaceous-creature** [comment]
I will push the package style i created yesterday, I think that style is easier for maintenance. You can check it later.

**Comment by tongtybj** [comment]
Ok. By the way,I also created a meta packages...


2016/01/05 11:19$B!"(BChen <notifications@github.com> $B$N%a%C%;!<%8(B:
