### ISSUE TITLE
pad model 

### ISSUE THREAD

**Issue by k-okada** [tongtybj/mbzirc#27]
are you still using https://github.com/tongtybj/mbzirc/tree/indigo-devel/jsk_mbzirc_common/gazebo_model/models/pad directory? if not please remove them

**Comment by k-okada** [comment]
or remove https://github.com/tongtybj/mbzirc/tree/indigo-devel/jsk_mbzirc_common/gazebo_model/models/eight

**Comment by k-okada** [comment]
Also please create pad model with multiple links,  at lest the valve must be a different link to be rotated.

**Comment by tongtybj** [comment]
Is this issue related with task2?
I am confused about the relationship between the pad and valve...
Maybe is should be "panel" which is the object in task2

2016-01-14 12:20 GMT+09:00 Kei Okada <notifications@github.com>:

**Comment by k-okada** [comment]
sorry, you're correct. I meant "panel" object of task2

--
◉ Kei Okada

**Comment by cretaceous-creature** [comment]
I have deleted the unnecessary models.....
For the wrenches, I made every wrench a model so that 
we can change the size and location in .world file more conveniently.
If there are better method, plz tell me.

**Comment by k-okada** [comment]
how about this one http://answers.gazebosim.org/question/8958/reuse-sdf-using-different-mesh-files/

**Comment by k-okada** [comment]
panel model itself seems great! thanks
