### ISSUE TITLE
new map got some problem

### ISSUE THREAD

**Issue by cretaceous-creature** [tongtybj/mbzirc#7]
I have modified the source code and add a patch, now the husky with ur5 would move correctly, but for the gripper action and moving base, still need some time....

and For the new map, I think the direction is wrong, plz commit after heavy test.

**Comment by cretaceous-creature** [comment]
Now I think you can install the husky simulation by README, just run ./install.

**Comment by tongtybj** [comment]
@cretaceous-creature 
> and For the new map, I think the direction is wrong, plz commit after heavy test.
which direction? is yaw? should I give a 90degree turn in yaw axis?

**Comment by tongtybj** [comment]
@cretaceous-creature 
some problem with install.sh

./install.sh 
Cloning into 'husky'...
remote: Counting objects: 2043, done.
remote: Total 2043 (delta 0), reused 0 (delta 0), pack-reused 2043
Receiving objects: 100% (2043/2043), 9.74 MiB | 696.00 KiB/s, done.
Resolving deltas: 100% (1191/1191), done.
Checking connectivity... done.
Cloning into 'husky_robot'...
remote: Counting objects: 1567, done.
remote: Total 1567 (delta 0), reused 0 (delta 0), pack-reused 1567
Receiving objects: 100% (1567/1567), 1.46 MiB | 405.00 KiB/s, done.
Resolving deltas: 100% (803/803), done.
Checking connectivity... done.
Cloning into 'husky_simulator'...
remote: Counting objects: 833, done.
remote: Total 833 (delta 0), reused 0 (delta 0), pack-reused 833
Receiving objects: 100% (833/833), 1.52 MiB | 483.00 KiB/s, done.
Resolving deltas: 100% (415/415), done.
Checking connectivity... done.
Cloning into 'husky_customization'...
remote: Counting objects: 50, done.
remote: Total 50 (delta 0), reused 0 (delta 0), pack-reused 50
Unpacking objects: 100% (50/50), done.
Checking connectivity... done.
Cloning into 'husky_desktop'...
remote: Counting objects: 630, done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 630 (delta 300), reused 630 (delta 300), pack-reused 0
Receiving objects: 100% (630/630), 1.26 MiB | 474.00 KiB/s, done.
Resolving deltas: 100% (300/300), done.
Checking connectivity... done.
Cloning into 'universal_robot'...
remote: Counting objects: 3595, done.
remote: Total 3595 (delta 0), reused 0 (delta 0), pack-reused 3595
Receiving objects: 100% (3595/3595), 27.12 MiB | 810.00 KiB/s, done.
Resolving deltas: 100% (2038/2038), done.
Checking connectivity... done.
Branch gripper-and-roscontrol-fix set up to track remote branch gripper-and-roscontrol-fix from origin.
Switched to a new branch 'gripper-and-roscontrol-fix'
Branch gripper-addition set up to track remote branch gripper-addition from origin.
Switched to a new branch 'gripper-addition'
cp: `../mbzirc/husky.patch' を stat できません: そのようなファイルやディレクトリはありません

chou@chou-desktop:~/ros/catkin_ws/src/mbzirc$ ./install.sh 
Cloning into 'husky'...
remote: Counting objects: 2043, done.
remote: Total 2043 (delta 0), reused 0 (delta 0), pack-reused 2043
Receiving objects: 100% (2043/2043), 9.74 MiB | 696.00 KiB/s, done.
Resolving deltas: 100% (1191/1191), done.
Checking connectivity... done.
Cloning into 'husky_robot'...
remote: Counting objects: 1567, done.
remote: Total 1567 (delta 0), reused 0 (delta 0), pack-reused 1567
Receiving objects: 100% (1567/1567), 1.46 MiB | 405.00 KiB/s, done.
Resolving deltas: 100% (803/803), done.
Checking connectivity... done.
Cloning into 'husky_simulator'...
remote: Counting objects: 833, done.
remote: Total 833 (delta 0), reused 0 (delta 0), pack-reused 833
Receiving objects: 100% (833/833), 1.52 MiB | 483.00 KiB/s, done.
Resolving deltas: 100% (415/415), done.
Checking connectivity... done.
Cloning into 'husky_customization'...
remote: Counting objects: 50, done.
remote: Total 50 (delta 0), reused 0 (delta 0), pack-reused 50
Unpacking objects: 100% (50/50), done.
Checking connectivity... done.
Cloning into 'husky_desktop'...
remote: Counting objects: 630, done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 630 (delta 300), reused 630 (delta 300), pack-reused 0
Receiving objects: 100% (630/630), 1.26 MiB | 474.00 KiB/s, done.
Resolving deltas: 100% (300/300), done.
Checking connectivity... done.
Cloning into 'universal_robot'...
remote: Counting objects: 3595, done.
remote: Total 3595 (delta 0), reused 0 (delta 0), pack-reused 3595
Receiving objects: 100% (3595/3595), 27.12 MiB | 810.00 KiB/s, done.
Resolving deltas: 100% (2038/2038), done.
Checking connectivity... done.
Branch gripper-and-roscontrol-fix set up to track remote branch gripper-and-roscontrol-fix from origin.
Switched to a new branch 'gripper-and-roscontrol-fix'
Branch gripper-addition set up to track remote branch gripper-addition from origin.
Switched to a new branch 'gripper-addition'
cp: `../mbzirc/husky.patch' を stat できません: そのようなファイルやディレクトリはありません

**Comment by tongtybj** [comment]
Maybe the "mbzirc/husky.patch" does not exist...

**Comment by cretaceous-creature** [comment]
I keng le again......  what the order of git to add all file and commit.....

2016-01-06 23:39 GMT+09:00 趙 漠居 <notifications@github.com>:

**Comment by cretaceous-creature** [comment]
debug finished, the yaw angle is wrong when i launch the package, 
and the robot should be a little bit higher by set the initial robot pose.
