### ISSUE TITLE
new arena can not open in some PC

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/mbzirc#8]
As mentioned in issue #7, the new arean can not open in Chen's pc.

But with my PCs, it can be seen in gazebo correctly.
One reason I think is the version of sdf.
WIht mine, the version is 1.4.
But I think the version of chen's pc is 1.5.

I will continue to tacke this problem

**Comment by cretaceous-creature** [comment]
I think because my ubuntu is 14.04 LTS3,  seems this version equip 1.5

2016-01-06 23:44 GMT+09:00 趙 漠居 <notifications@github.com>:

**Comment by tongtybj** [comment]
我的也是14.04……，不知道是不是version3

2016-01-07 11:37 GMT+09:00 Chen <notifications@github.com>:
