### ISSUE TITLE
the path in setup.sh seem to be wrong

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/mbzirc#9]
@cretaceous-creature 

the path written in setup.sh:

port GAZEBO_MODEL_PATH=`rospack find jsk_mbzirc_common`/../../src/mbzirc/gazebo_model/models:$GAZEBO_MODEL_PATH
export GAZEBO_RESOURCE_PATH=`rospack find jsk_mbzirc_common`/../../src/mbzirc/gazebo_model/world:$GAZEBO_RESOURCE_PATH

seem to be wrong...

the right path should be:
port GAZEBO_MODEL_PATH=`rospack find jsk_mbzirc_common`/../../mbzirc/gazebo_model/models:$GAZEBO_MODEL_PATH
export GAZEBO_RESOURCE_PATH=`rospack find jsk_mbzirc_common`/../../mbzirc/gazebo_model/world:$GAZEBO_RESOURCE_PATH

**Comment by cretaceous-creature** [comment]
Yeah, here I did not test,
and since you want to move the gazebo_model under the jsk_mbzirc_common,
just change to the final one..

**Comment by cretaceous-creature** [comment]
because now my rospack find will go to the install/ path, I will fix that later...
